[[redirects]]
  from = "/app/*"
  to = "/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    disabled = true