const SITEMAP_GROUPS = [
  {
    title: "Main Pages",
    items: [
      { label: "Home", routeKey: "home", href: "/" },
      { label: "About", routeKey: "about", href: "/about" },
      { label: "Features", routeKey: "features", href: "/features" },
      { label: "Partners", routeKey: "partners", href: "/partners" },
      {
        label: "Contact",
        routeKey: "contact",
        href: "/contact",
        fallbackRouteKey: "contact",
      },
      { label: "Preview", routeKey: "preview", href: "/preview" },
      {
        label: "Early Access",
        routeKey: "early-access",
        href: "/early-access",
        fallbackRouteKey: "preview",
      },
    ],
  },
  {
    title: "Legal",
    items: [
      { label: "Privacy Policy", routeKey: "privacy", href: "/privacy" },
      { label: "Terms of Use", routeKey: "terms", href: "/terms" },
    ],
  },
  {
    title: "Product / System Pages",
    items: [
      {
        label: "How ZWAP Works",
        routeKey: "how-zwap-works",
        href: "/how-zwap-works",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "Rewards System",
        routeKey: "rewards-system",
        href: "/rewards-system",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "zPts and ZWAP",
        routeKey: "zpts-and-zwap",
        href: "/zpts-and-zwap",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "Move",
        routeKey: "move",
        href: "/move",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Play",
        routeKey: "play",
        href: "/play",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Shop",
        routeKey: "shop",
        href: "/shop",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Learn",
        routeKey: "learn",
        href: "/learn",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Stream",
        routeKey: "stream",
        href: "/stream",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Garden",
        routeKey: "garden",
        href: "/garden",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Badges",
        routeKey: "badges",
        href: "/badges",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Sponsor Rewards",
        routeKey: "sponsor-rewards",
        href: "/sponsor-rewards",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Swap",
        routeKey: "swap",
        href: "/swap",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
    ],
  },
  {
    title: "Partner / Business Pages",
    items: [
      {
        label: "Sponsor Opportunities",
        routeKey: "sponsor-opportunities",
        href: "/sponsor-opportunities",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
      {
        label: "Enterprise Wellness",
        routeKey: "enterprise-wellness",
        href: "/enterprise-wellness",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
      {
        label: "Financial Literacy Programs",
        routeKey: "financial-literacy-programs",
        href: "/financial-literacy-programs",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
      {
        label: "Community Partnerships",
        routeKey: "community-partnerships",
        href: "/community-partnerships",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
      {
        label: "Developer Portal",
        routeKey: "developer-portal",
        href: "/developer-portal",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
    ],
  },
  {
    title: "Content / Articles",
    items: [
      {
        label: "Blog",
        routeKey: "blog",
        href: "/blog",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "Latest Updates",
        routeKey: "latest-updates",
        href: "/latest-updates",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "Financial Literacy",
        routeKey: "financial-literacy",
        href: "/financial-literacy",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Wellness and Movement",
        routeKey: "wellness-and-movement",
        href: "/wellness-and-movement",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Crypto Basics",
        routeKey: "crypto-basics",
        href: "/crypto-basics",
        comingSoon: true,
        fallbackRouteKey: "about",
      },
      {
        label: "Rewards and Retention",
        routeKey: "rewards-and-retention",
        href: "/rewards-and-retention",
        comingSoon: true,
        fallbackRouteKey: "features",
      },
      {
        label: "Sponsor News",
        routeKey: "sponsor-news",
        href: "/sponsor-news",
        comingSoon: true,
        fallbackRouteKey: "partners",
      },
    ],
  },
];